### PR TITLE
 * Added support for singleton locators per thread

### PR DESCRIPTION
**Pull request by eemmiirr**

### CODE REVIEW

**Comment by adrianluisgonzalez** [comment]
Can you describe the use case for this?  You don't control which event loop thread your verticle is deployed on, nor which other verticles may run on the same event loop...

**Comment by eemmiirr** [comment]
So basically i want to configure something in one verticle and share it with the other verticles which are running on the same thread. It will still create one hk2 context per thread. All verticles which run on the same thread will share the same context which actually makes sense for a lot of use cases since they don't need a context per verticle. It will also lower the memory usage. I added a switch so per default it's not enabled.

**Comment by adrianluisgonzalez** [comment]
Sorry, I still don't understand the scenario where this gives a predictable outcome.  Using the default event loop sizing (2 * # of cores), if I deploy 6 verticles on a 3 core machine each verticle will be on its own event loop thread, but on a 2 core machine some verticles will share event loop threads.  As soon as verticles start deploying sub verticles, it becomes even less predictable.

What is the reason for only sharing instances on an event loop thread rather than across all verticles with the parent locator?  A concrete example would help me understand.

**Comment by eemmiirr** [comment]
In general the context should be imutable once created. In general if it's imutable it doesn't make sense to recreate the same context over and over again for other verticles which run on the same thread. For instance i need to configure a connection pool for cassandra which i want to have once per thread and not per verticle since i have jersey, scheduler and kafka verticles which can reuse it from the same thread since they will never run in parallel.

**Comment by eemmiirr** [comment]
I have one more example. When i use https://github.com/ef-labs/vertx-cassandra CassandraSession class which is mutable i would have big problems if i share it between threads with the parent locator. It has a Session object inside which can change on reconection. If it's only one context per thread it doesn't matter since it won't be synced and i won't run into race conditions

**Comment by marcust** [comment]
We had another use-case for this a while ago. Using the vertx-elasticsearch-service and vertx-jersey we wanted to expose the actual Elasticsearch Client for a health check endpoint to make sure that the client is still connected and fine. There is no way to do this either at the moment.

**Comment by adrianluisgonzalez** [comment]
@eemmiirr, the datastax cassandra session is thread safe: http://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/Session.html

> Session instances are thread-safe and usually a single instance is enough per application.

@marcust, that is what the parent locator is intended for.  I will push an example using the parent locator.

**Comment by eemmiirr** [comment]
@adrianluisgonzalez yes it is but it can get replaced with a new one on reconnect. CassandraSession from https://github.com/ef-labs/vertx-cassandra is not. But anyway is the intention of vertx not to have shared data between threads to avoid syncronisations and locks. Even the shared data structure provided by vertx makes a copy for each thread

**Comment by adrianluisgonzalez** [comment]
Vert.x shared data returns the same map instance, see SharedDataImpl:

```java
  /**
   * Return a {@code Map} with the specific {@code name}. All invocations of this method with the same value of {@code name}
   * are guaranteed to return the same {@code Map} instance. <p>
   */
  @SuppressWarnings("unchecked")
  public <K, V> LocalMap<K, V> getLocalMap(String name) {
```

`vertx-hk2` tries to follow this pattern, it either creates a locator per verticle to isolate resources or shares a parent service locator globally for immutable or thread safe objects.

Can you point to where vertx-cassandra is not thread safe?  If you could open an issue in that repo that would be great.  Thanks.

**Comment by eemmiirr** [comment]
@adrianluisgonzalez yes you are right with the map it's a ConcurrentMap. As far as i remember in the vertx 2.x.x it was a map that was coppied. 

Regarding the parent locator maybe it makes sense to share data but not really connections to DBs. 
If you look at DefaultCassandraSession

```java
private Cluster.Builder clusterBuilder;
private final Vertx vertx;
private List<Handler<AsyncResult<Void>>> onReadyCallbacks = new ArrayList<>();

protected Cluster cluster;
protected Session session;
protected Metrics metrics;
protected CassandraConfigurator configurator;
protected AsyncResult<Void> initResult;
```

you can see that session is just a field.

Then there is the reconect method which changes it.
```java
    @Override
    public void reconnect() {
        logger.debug("Call to reconnect the session has been made");
        Session oldSession = session;
        session = cluster.connect();
        if (oldSession != null) {
            oldSession.closeAsync();
        }
        metrics.afterReconnect();
    }
```

So if one thread changes the session there is no guaranty that the other thread will see that change. To solve this you would need to introduce some form of locking. In my opinion the eventloop threads shouldn't go through looks if not really needed. They would get blocked for some time which shouldn't really happen if it can be avoided. So with a locator per thread every thread will have a copy of the context and the code can be developed in a single threaded manner which will increase the performance. IMHO the developer should be able to choose if he wants to have a shared resource with locks using the parent locator or to have a context per thread (not per verticle since it doesn't make sense to re-generate the same context for verticles running on the same thread for most use cases). Thats why i also added a switch to enable a singleton per thread if it's desired

**Comment by eemmiirr** [comment]
@adrianluisgonzalez i redesigned the caching so it's predictable. It caches based on the parent locator, classloader, bootstrap loader classes and thread. So basically even when verticles deploy verticles they will have their own locators if the context config changes in any way. I tested it on our more complicated projects and it works without problems. So now if the verticles live in the same environment they have the same context per thread which removed unncesery locks and increases performance

**Comment by adrianluisgonzalez** [comment]
Apologies for the radio silence, I have been out of office.

I am concerned about adding a dependency to `commons-collections4`.  I would suggest either reworking this to not require the new dependency, alternatively the `HK2VerticleLoader` class could be instantiated by a service locator to allow extensibility.

**Pull request closed without merging**
